language: python
sudo: required
python:
    - "2.7"
env:
    - PGVERSION=9.1 CKAN_BRANCH=master
    - PGVERSION=9.1 CKAN_BRANCH=release-v2.3
    - PGVERSION=9.1 CKAN_BRANCH=release-v2.5.1
install:
    - bash bin/travis-build.bash
    - pip install coveralls
script: sh bin/travis-run.sh
after_success:
    - coveralls
